language: node_js
node_js:
- lts/boron
cache:
  directories:
  - node_modules
before_install: 
deploy:
  provider: npm
  email: 
  api_key:
    secure: OsA79weHdx7PvBXzEvOmuiBpIzqUdIC6cLwPq/kwngI+XWgBoGvVTYw69GpsMeuiNZUVkcxDpfx+6Zh5HPI9K1mthTNPtycFsAZrtc3utMixghkYU6YfB6/16hu+Uc/w4fusOqUR13QE3f+SEZtJTeO0oOFkdKBX2WTUpb5QRJtSsytYgvwPR5zaCFhAUXvkdSZvRAttUzhPCTymX07h2CbZC3XKOSLSD9mk7MQLB7lsa3eiuxuFtDOCICeel/gmfeSSGH9tnvZiNjH97cOVVchmhgjBFKKvFKUmjfN6RY4P6xnMwchRehZ1jRW8mgCHUH3h+neQqhhOkeLicBd2h10mCwNC8g8HmbZpT6TfW7Zs1TUcr40dRcKl5Ch50lmOqwJFAhVpg8kxidNgT7ADliAH/deVBoPOltI78VRh5dyo3Klu2A5ZykWC/xXkLhQeXciJxEX0klXEO9jUAjkkouSwgjuZvZKZkPFvUwNh5PCTD8DuyNpjpDQsTpikEc3eafkYipwUYfkXX9Kd5zKfuYb/CbKTw2h0wMp8Sw81qRDelCzNRQT+5+gHYoLkIYhHHgXGT9Nxi0nL0MZAJ1BOFV6hc/BvCv9fsNwisnjZ8nPPN53TKc1t/NxZo4LSDL6RFZ3eYJiQOfnTtM5m27Wv8/2vr62eLAJv4Pb64cy9HPc=
  on:
    tags: true
notifications:
  hipchat:
    rooms:
      secure: pVxr2cFFRAwH+mn6VqM41kUkKqt+rfzbh17RUAsUAjS3zRcd9yk5U+1YCxZ9/GfLiFkfnoL3pCviRtkq5hhON9e3UAFjrDM+XqfTclHxx6ePT0EUFHF/Nd22XPyEqmuKEZd/ORM06PZOZWdg0jrKZ+gEV6UMLZzSA7FjBaMwc7yjPJ2j0fHzHmTI8nCQlL4uncn3nbHa8W3Kv45O/eAOr/J42/7UI69o1iF3tiOLVLV1lDjR6N7sWjtQxj/nT33iNgGlTZlFJdXmyBJD50L9RiKFvxgzGtqYF2yBx+wd826Wew5B+6KTlPZEL3uZTJ0gNNrNvGggnLx5iS4rN9sfVpSuahp3rpjTAqkW1NaIxGoS4OAxNdO0MjckNFRCnN1ygXh8MbD38T88naC9Ds1PFmdElItu3o4e0upD5P4xfmwX1a427tCPHtJGzgG3XD787HjpFCpPCFWQaSKscKccGQ9EnpqSKIOABq0MlUrDQdAWFCVGHypG9wdDNjq0YXFRuPjeqfcyf4eib0bz7FoQAgddgUPHLluQsLhWU7DNZtUifl4Voxuo07tr0FwJURzThth6L4Hhk9RlbywWAi0JrxmQPDLsfMulaXz2mb+xI7OffswsnLzeQifRyLYQfDts+eDw0YGyvXQcYBpRlGJe7C1dFvynv+u+SrlYCtwQZOI=
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
