language: node_js
node_js:
- lts/boron
cache:
  directories:
  - node_modules
before_install: 
deploy:
  provider: npm
  email: geert.premereur+awv@ictects.com
  api_key:
    secure: OsA79weHdx7PvBXzEvOmuiBpIzqUdIC6cLwPq/kwngI+XWgBoGvVTYw69GpsMeuiNZUVkcxDpfx+6Zh5HPI9K1mthTNPtycFsAZrtc3utMixghkYU6YfB6/16hu+Uc/w4fusOqUR13QE3f+SEZtJTeO0oOFkdKBX2WTUpb5QRJtSsytYgvwPR5zaCFhAUXvkdSZvRAttUzhPCTymX07h2CbZC3XKOSLSD9mk7MQLB7lsa3eiuxuFtDOCICeel/gmfeSSGH9tnvZiNjH97cOVVchmhgjBFKKvFKUmjfN6RY4P6xnMwchRehZ1jRW8mgCHUH3h+neQqhhOkeLicBd2h10mCwNC8g8HmbZpT6TfW7Zs1TUcr40dRcKl5Ch50lmOqwJFAhVpg8kxidNgT7ADliAH/deVBoPOltI78VRh5dyo3Klu2A5ZykWC/xXkLhQeXciJxEX0klXEO9jUAjkkouSwgjuZvZKZkPFvUwNh5PCTD8DuyNpjpDQsTpikEc3eafkYipwUYfkXX9Kd5zKfuYb/CbKTw2h0wMp8Sw81qRDelCzNRQT+5+gHYoLkIYhHHgXGT9Nxi0nL0MZAJ1BOFV6hc/BvCv9fsNwisnjZ8nPPN53TKc1t/NxZo4LSDL6RFZ3eYJiQOfnTtM5m27Wv8/2vr62eLAJv4Pb64cy9HPc=
  on:
    tags: true
notifications:
  hipchat:
    rooms:
      secure: Y3ktCQtIz6GB3jopjAJSMD52I7qBMQaQojQtmXleSlWuQjbyU8mQSewF4uh0cAVrAybFEK+1OzH0kKYwIvqJk6hcw8lG7QR7e5xm3DuuMrsbDbT5/us9P1A0lw61UMr+TaWneKyZAfNBuBeysdqTOaYyuh7bZlC4jNoWfZxRitKv9jPzs61yZjVTXMkmQ471UO/yiE8FVnNk8Uh6IxUz0LyXOyeansTvYDNldCvIjqJ+bConOdRJleOzitQ2b5OdN91OzC+3Xjd9e+9MzWAkOPNmwOen3CKfcFSEA0sdpC1RZGzyU9cB2+a2VwwGPMoCOXWC8TrhH9P8Rn8VYwhtu4dSD00xzy17/NRO0x4PNLoDMKNhrWtl5bUud4cO4qSkYmXV3+21RZ4/UganxaMYNS59wqfoqGMiCAupoxki4ZUvyEAcgwRSRQaw+eSHQQ2UNmWR5MLhxV9zKcL/uwsCGy+XM0NgJED/U2HPDHJsH9orN2/8G2nk7W700LYr3MYMfEcV/HWHieT8WKyg0Cc/971twKQnJaS5mgyE1dHgPyVmMXLYm5ZGTNbpOyxC/8fhj2Hc/YAeyNAZ8TlRahqXhYPJKFHV/haS/tlIN4/5aVxVfOoO+sHR1WJHMX+3wn+v+b3q7Hmt6bqF3HJJ993U502PQsE/gEDTkrQoWHLIlu4=
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
