language: node_js
node_js:
- lts/boron
cache:
  directories:
  - node_modules
before_install: 
deploy:
  provider: npm
  email: geert.premereur+awv@ictects.com
  api_key:
    secure: WKlh7zNVTkaviTyX1rpdM/IvK+FqPCYF0Qkzad3WonkC9hYGnva/jhNk/+MQ/1o/SmccluBFn2xYe51l76f3v7VnL5GANjlmQ6gslWypU0woavAV1nIG131JDJlLNoHP8aPQlRn22sDd0oTcIjCzDfUOCVSJ4X76KvwwHd0BUKOMagG1f0GB6YG3YA7kFki3x5Xjus5/OA5Kwx7oCuaiwkiEk8pUYDno+iyFvfb2LOxneRQWryG0q5cCnq7s1R1iGI87W699x3eVKQRS/ogbOnJkfItER84t1mbb5VChWKjLVjiLrItqbwgkccl1gypsqNvzLLsa8FvGUE3M/G9xjs2lscfQEXXoePZBaU0uLuLfgHbYJTJNcMqbZliF5UqhgZQfM6p0OasDpEYjz/x4dfPyQNrUmgZUqOR/0tpyiy5ZIGgNJA+jI71oih9LtKoh81nGj3pg0Mgg0QJS4fI8elDEnd8tQgfLcrMWiJAmpuzucX8WwDoiyVvDHI8Kd4hrnwpj52XRFAqrsSPIBsJGJZOZQGaND1z/BeuaCWs3RYOqaCVhbW2hOxo+c8l3jUdnTVrrSoaEyB2Gt5himmvOw8j07qrSbALaAYZwmqmMDQeiu+cyWH30wDnFb7Aot830yICD14TdI9KHuooexyNG5Z4Qz//niC5p2saowfrTaXQ=
  on:
    tags: true
notifications:
  hipchat:
    rooms:
      secure: Y3ktCQtIz6GB3jopjAJSMD52I7qBMQaQojQtmXleSlWuQjbyU8mQSewF4uh0cAVrAybFEK+1OzH0kKYwIvqJk6hcw8lG7QR7e5xm3DuuMrsbDbT5/us9P1A0lw61UMr+TaWneKyZAfNBuBeysdqTOaYyuh7bZlC4jNoWfZxRitKv9jPzs61yZjVTXMkmQ471UO/yiE8FVnNk8Uh6IxUz0LyXOyeansTvYDNldCvIjqJ+bConOdRJleOzitQ2b5OdN91OzC+3Xjd9e+9MzWAkOPNmwOen3CKfcFSEA0sdpC1RZGzyU9cB2+a2VwwGPMoCOXWC8TrhH9P8Rn8VYwhtu4dSD00xzy17/NRO0x4PNLoDMKNhrWtl5bUud4cO4qSkYmXV3+21RZ4/UganxaMYNS59wqfoqGMiCAupoxki4ZUvyEAcgwRSRQaw+eSHQQ2UNmWR5MLhxV9zKcL/uwsCGy+XM0NgJED/U2HPDHJsH9orN2/8G2nk7W700LYr3MYMfEcV/HWHieT8WKyg0Cc/971twKQnJaS5mgyE1dHgPyVmMXLYm5ZGTNbpOyxC/8fhj2Hc/YAeyNAZ8TlRahqXhYPJKFHV/haS/tlIN4/5aVxVfOoO+sHR1WJHMX+3wn+v+b3q7Hmt6bqF3HJJ993U502PQsE/gEDTkrQoWHLIlu4=
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
