language: node_js
node_js:
- lts/boron
cache:
  directories:
  - node_modules
before_install: 
deploy:
  provider: npm
  email: geert.premereur+awv@ictects.com
  api_key:
    secure: '08lA58qfq6kBh+t/9AyxPfdxES38aQjuU0beFGbdVW4kyNeurzssgAgQxrGBH5k8TZudIslYRxZLQM0SD1m9VDohx6anKtydg4RqUFxfY6gxjiAIGeTme1rjMsWLTyFQ7asYKDkOrY4f+y6ZSR4UBUuETNGXTKFFdOT1Tqv1RxqE/x2788LBY6RNN6Iyb53uFk5D5PHW+IjRm/djvxO/l61I/RiFDLiir3ILUTnfokFBvtThUJgaBCUEm6cWW1BGSZFBiwT/fwsZDnRrjJbkG7aMB1orA0O+8RBqh5eOREPCgZ/H5NuWRaFJYmRMCYA8dK28JyMZ76uOUiaoCNQuIPgaLE0b9/BqKbSKGsns5CvDmpkXMdTwKK7g67OvXVl1lezKE2o+hYtprOJm2QHHm+jXlBgzUmDsVbanLTS8Lsjzjo1xRre+FZSgU/TzF9/8Xu0BorwK+IJ6f6vF97IEzE68BAaPROC+X3Zh/qBwlTT9OYUJJsSTfF/pVXOpDFfE4A85aYiw23yCQNfySs6po6F4lSgr8LH0QXZ1GvMWNA6HQDayZxx5BwRne5BKjOfqPh25b/S/xZ+GIR8JzX8Mx6Mj8AnztYj/FywdsxBbqjkb0kg06sQW/5lc8QvgoozA+HON+qNrHQZftcyb+M9cZBcPAZqFiSxUB8uMopJEV8M='
  on:
    tags: true
notifications:
  hipchat:
    rooms:
      secure: Y3ktCQtIz6GB3jopjAJSMD52I7qBMQaQojQtmXleSlWuQjbyU8mQSewF4uh0cAVrAybFEK+1OzH0kKYwIvqJk6hcw8lG7QR7e5xm3DuuMrsbDbT5/us9P1A0lw61UMr+TaWneKyZAfNBuBeysdqTOaYyuh7bZlC4jNoWfZxRitKv9jPzs61yZjVTXMkmQ471UO/yiE8FVnNk8Uh6IxUz0LyXOyeansTvYDNldCvIjqJ+bConOdRJleOzitQ2b5OdN91OzC+3Xjd9e+9MzWAkOPNmwOen3CKfcFSEA0sdpC1RZGzyU9cB2+a2VwwGPMoCOXWC8TrhH9P8Rn8VYwhtu4dSD00xzy17/NRO0x4PNLoDMKNhrWtl5bUud4cO4qSkYmXV3+21RZ4/UganxaMYNS59wqfoqGMiCAupoxki4ZUvyEAcgwRSRQaw+eSHQQ2UNmWR5MLhxV9zKcL/uwsCGy+XM0NgJED/U2HPDHJsH9orN2/8G2nk7W700LYr3MYMfEcV/HWHieT8WKyg0Cc/971twKQnJaS5mgyE1dHgPyVmMXLYm5ZGTNbpOyxC/8fhj2Hc/YAeyNAZ8TlRahqXhYPJKFHV/haS/tlIN4/5aVxVfOoO+sHR1WJHMX+3wn+v+b3q7Hmt6bqF3HJJ993U502PQsE/gEDTkrQoWHLIlu4=
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
