language: node_js
node_js:
- lts/boron
cache:
  directories:
  - node_modules
before_install: 
deploy:
  provider: npm
  email: geert.premereur+awv@ictects.com
  api_key:
    secure: od/vaNteOkVZ6zkZEaWNaU/Jo18QIVDAS4112gqqljwh7vX4HqV4bcy9nRQcKGjXVCT9sGzB+Wkteb7+cYJclJJGVBXCmDO9KIABbq2gyUconGDZXE3hs8k1Vgb8EqA6/RTEORfQUu2HukXwLO1Ha4F56oFCv9Vb8W4kIlU+XPuGsd/TdgWhFSZFgAvvcuN9pGrpo6JrqpcKEP9enUKuYecEX33SmqTpVU+p1Kle2yqvvXdnRfLXt8p6t7ZGW4RQEst51Qgr/G/bdpNStHAqLxVKnBJ6FrEzweN65r0I7Yf94lOYuuJh+0Fq6elhCbDSluAHIlkFQXboOakxnBHzDS4mBcQtWe1Lg/NY/IifMtItNhKgEA7K8mSGmQv/wsK8dWCEW//8NyPsU8Sr+vJG4+I1S0h2oBRDR7xQL61IFe3lPL+3zvXuVSr2gBNUcS0lIvRUnn35XSFJLAdyncyC9fqwhqC+Bw0bidD/3W03o/AXsMlhuRqcSoiQZrChtF1RjDv8VsOrx26to+QD/Pub+M8AaepJ9qFwyBaMO4h6p4C56X2LO4dkR74BSNcta9p4QMaIJ+E3qXtjn9WQOFzr4tGR7HjeiuuoeVyTGb1J5W+5k9BpCkSlU+oxR9qWFLOZDkZjiowFlCSGLDrAIjxJGZCa/jxgusI5/DgezpxbebQ=
  on:
    tags: true
notifications:
  hipchat:
    rooms:
      secure: Y3ktCQtIz6GB3jopjAJSMD52I7qBMQaQojQtmXleSlWuQjbyU8mQSewF4uh0cAVrAybFEK+1OzH0kKYwIvqJk6hcw8lG7QR7e5xm3DuuMrsbDbT5/us9P1A0lw61UMr+TaWneKyZAfNBuBeysdqTOaYyuh7bZlC4jNoWfZxRitKv9jPzs61yZjVTXMkmQ471UO/yiE8FVnNk8Uh6IxUz0LyXOyeansTvYDNldCvIjqJ+bConOdRJleOzitQ2b5OdN91OzC+3Xjd9e+9MzWAkOPNmwOen3CKfcFSEA0sdpC1RZGzyU9cB2+a2VwwGPMoCOXWC8TrhH9P8Rn8VYwhtu4dSD00xzy17/NRO0x4PNLoDMKNhrWtl5bUud4cO4qSkYmXV3+21RZ4/UganxaMYNS59wqfoqGMiCAupoxki4ZUvyEAcgwRSRQaw+eSHQQ2UNmWR5MLhxV9zKcL/uwsCGy+XM0NgJED/U2HPDHJsH9orN2/8G2nk7W700LYr3MYMfEcV/HWHieT8WKyg0Cc/971twKQnJaS5mgyE1dHgPyVmMXLYm5ZGTNbpOyxC/8fhj2Hc/YAeyNAZ8TlRahqXhYPJKFHV/haS/tlIN4/5aVxVfOoO+sHR1WJHMX+3wn+v+b3q7Hmt6bqF3HJJ993U502PQsE/gEDTkrQoWHLIlu4=
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
